# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 01:19
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=140)),
                ('oauth_token', models.CharField(blank=True, max_length=50)),
                ('oauth_token_secret', models.CharField(blank=True, max_length=45)),
                ('friends_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), null=True, size=None)),
                ('followers_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), null=True, size=None)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
