# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 11:42
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('oauth_token', models.CharField(blank=True, max_length=50)),
                ('oauth_token_secret', models.CharField(blank=True, max_length=45)),
                ('friends_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), null=True, size=None)),
                ('followers_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), null=True, size=None)),
                ('last_refresh', models.DateTimeField(null=True)),
                ('gender', models.CharField(choices=[('unknown', 'unrecognized'), ('andy', 'either'), ('male', 'male (probably)'), ('female', 'female (probably)'), ('mostly_male', 'male (maybe)'), ('mostly_female', 'female (maybe)')], default='unknown', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='twitterlytic.TwitterProfile')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='twitterlytic.TwitterProfile')),
            ],
        ),
        migrations.AddField(
            model_name='twitterprofile',
            name='followers',
            field=models.ManyToManyField(through='twitterlytic.TwitterRelationship', to='twitterlytic.TwitterProfile'),
        ),
        migrations.AddField(
            model_name='twitterprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='twitterrelationship',
            unique_together=set([('followed', 'follower')]),
        ),
    ]
