# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterlytic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterprofile',
            name='gender',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('andy', 'Ambig/Neutral'), ('male', 'Male'), ('female', 'Female'), ('mostly_male', 'Likely male'), ('mostly_female', 'Likely female')], default='unknown', max_length=13),
        ),
    ]
