# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterlytic', '0004_twitterquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterprofile',
            name='followers_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='twitterprofile',
            name='friends_ratio',
            field=models.FloatField(null=True),
        ),
    ]
